spring.application.name=api-gateway

server.port=8755

eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.gateway.routes[0].id=medicamento
spring.cloud.gateway.routes[0].uri=lb://medicamento
spring.cloud.gateway.routes[0].predicates[0]=Path=/medicamento/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=user
spring.cloud.gateway.routes[1].uri=lb://user
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=agenda
spring.cloud.gateway.routes[2].uri=lb://agenda
spring.cloud.gateway.routes[2].predicates[0]=Path=/agenda/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1
