spring.application.name=name-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF

server.port=8761

server.ssl.key-store=classpath:mei_aid.jks
server.ssl.key-store-password=aluno123
server.ssl.key-store-type=JKS
server.ssl.key-alias=mei-aid-cert

server.ssl.client-auth=none

server.ssl.enabled=true 

logging.level.org.springframework.boot.web.embedded.tomcat=DEBUG
