name: meditrack
description: "Meditrack - seu medicamento controlado"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  syncfusion_flutter_calendar: ^29.2.4
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
